name:        togglemon
version:     0.1.0
synopsis:    A simple program for toggling displays via xrandr.
github:      dogonthehorizon/togglemon
license:     MIT
author:      Fernando Freire
maintainer:  Fernando Freire <dogonthehorizon@gmail.com>
copyright:   2019 Fernando Freire
category:    CLI
extra-source-files:
- README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-partial-type-signatures
  - -fno-warn-name-shadowing
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-incomplete-patterns


default-extensions:
  - BangPatterns
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables
  - TemplateHaskell

dependencies:
  - base >= 4.7 && < 5
  - directory
  - filepath
  - lens
  - mtl
  - text

executables:
  togglemon:
    source-dirs:      src
    main:             Main.hs

internal-libraries:
  togglemon-internal:
    source-dirs: src

tests:
  togglemon-test:
    main: Tasty.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - togglemon-internal
      - smallcheck
      - smallcheck-series
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-smallcheck
      - text
