name:        memorable-name
version:     0.2.0
synopsis:    A simple program for generating memorable names in the adjective-noun style.
github:      dogonthehorizon/togglemon
license:     MIT
author:      Fernando Freire
maintainer:  Fernando Freire <dogonthehorizon@gmail.com>
copyright:   2019 Fernando Freire
category:    CLI

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-partial-type-signatures
  - -fno-warn-name-shadowing
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-incomplete-patterns

default-extensions:
  - BangPatterns
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables
  - TemplateHaskell

dependencies:
  - base >= 4.7 && < 5
  - random
  - mtl

library:
  source-dirs: src
  
tests:
  memorable-name-test:
    main: Tasty.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wno-missing-signatures
    dependencies:
      - memorable-name
      - smallcheck
      - smallcheck-series
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-smallcheck
