name:        edid
version:     0.1.0
synopsis:    Parser for EDID formats
github:      dogonthehorizon/togglemon
license:     MIT
author:      Fernando Freire
maintainer:  Fernando Freire <dogonthehorizon@gmail.com>
copyright:   2019 Fernando Freire
category:    Parser

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-partial-type-signatures
  - -fno-warn-name-shadowing
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-incomplete-patterns


default-extensions:
  - BangPatterns
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables
  - TemplateHaskell

dependencies:
  - base >= 4.7 && < 5
  
library:
  source-dirs: src
  dependencies:
    - bytestring
    - cereal

tests:
  edid-test:
    main: Tasty.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - edid
      - smallcheck
      - smallcheck-series
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-smallcheck
      - text
      - unordered-containers
